### ISSUE TITLE
PHP v7.1.0 notices

### ISSUE THREAD

**Issue by alexxgermann** [parallelus/static_content_blocks#5]
A customer is reporting seeing more errors with PHP v7.1.0...

>Warning: Illegal string offset ‘id’ in /home/nygrenli/public_html/dev/wp-content/plugins/static_content_blocks/post-type-static-block.php on line 38
>
>Warning: array_merge(): Argument #2 is not an array in /home/nygrenli/public_html/dev/wp-content/plugins/static_content_blocks/post-type-static-block.php on line 107

**Help Center topic** → http://para.llel.us/support/groups/goexplore/forum/topic/problem-with-php-7-1/#post-87866

**Comment by alexxgermann** [comment]
@jeffwalker99 
Please provide the client with the latest version of the plugin from the branch **develop** for checking the fixes

**Comment by jeffwalker99** [comment]
I've posted the changes in the Help Center, awaiting feedback from the customer.
